# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='Security.proto',
  package='hadoop.common',
  serialized_pb='\n\x0eSecurity.proto\x12\rhadoop.common\"Q\n\nTokenProto\x12\x12\n\nidentifier\x18\x01 \x02(\x0c\x12\x10\n\x08password\x18\x02 \x02(\x0c\x12\x0c\n\x04kind\x18\x03 \x02(\t\x12\x0f\n\x07service\x18\x04 \x02(\t\"1\n\x1eGetDelegationTokenRequestProto\x12\x0f\n\x07renewer\x18\x01 \x02(\t\"K\n\x1fGetDelegationTokenResponseProto\x12(\n\x05token\x18\x01 \x01(\x0b\x32\x19.hadoop.common.TokenProto\"L\n RenewDelegationTokenRequestProto\x12(\n\x05token\x18\x01 \x02(\x0b\x32\x19.hadoop.common.TokenProto\":\n!RenewDelegationTokenResponseProto\x12\x15\n\rnewExpiryTime\x18\x01 \x02(\x04\"M\n!CancelDelegationTokenRequestProto\x12(\n\x05token\x18\x01 \x02(\x0b\x32\x19.hadoop.common.TokenProto\"$\n\"CancelDelegationTokenResponseProtoB8\n org.apache.hadoop.security.protoB\x0eSecurityProtos\x88\x01\x01\xa0\x01\x01')




_TOKENPROTO = descriptor.Descriptor(
  name='TokenProto',
  full_name='hadoop.common.TokenProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='identifier', full_name='hadoop.common.TokenProto.identifier', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='hadoop.common.TokenProto.password', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kind', full_name='hadoop.common.TokenProto.kind', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='service', full_name='hadoop.common.TokenProto.service', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=114,
)


_GETDELEGATIONTOKENREQUESTPROTO = descriptor.Descriptor(
  name='GetDelegationTokenRequestProto',
  full_name='hadoop.common.GetDelegationTokenRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='renewer', full_name='hadoop.common.GetDelegationTokenRequestProto.renewer', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=116,
  serialized_end=165,
)


_GETDELEGATIONTOKENRESPONSEPROTO = descriptor.Descriptor(
  name='GetDelegationTokenResponseProto',
  full_name='hadoop.common.GetDelegationTokenResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='token', full_name='hadoop.common.GetDelegationTokenResponseProto.token', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=167,
  serialized_end=242,
)


_RENEWDELEGATIONTOKENREQUESTPROTO = descriptor.Descriptor(
  name='RenewDelegationTokenRequestProto',
  full_name='hadoop.common.RenewDelegationTokenRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='token', full_name='hadoop.common.RenewDelegationTokenRequestProto.token', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=244,
  serialized_end=320,
)


_RENEWDELEGATIONTOKENRESPONSEPROTO = descriptor.Descriptor(
  name='RenewDelegationTokenResponseProto',
  full_name='hadoop.common.RenewDelegationTokenResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='newExpiryTime', full_name='hadoop.common.RenewDelegationTokenResponseProto.newExpiryTime', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=322,
  serialized_end=380,
)


_CANCELDELEGATIONTOKENREQUESTPROTO = descriptor.Descriptor(
  name='CancelDelegationTokenRequestProto',
  full_name='hadoop.common.CancelDelegationTokenRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='token', full_name='hadoop.common.CancelDelegationTokenRequestProto.token', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=382,
  serialized_end=459,
)


_CANCELDELEGATIONTOKENRESPONSEPROTO = descriptor.Descriptor(
  name='CancelDelegationTokenResponseProto',
  full_name='hadoop.common.CancelDelegationTokenResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=461,
  serialized_end=497,
)

_GETDELEGATIONTOKENRESPONSEPROTO.fields_by_name['token'].message_type = _TOKENPROTO
_RENEWDELEGATIONTOKENREQUESTPROTO.fields_by_name['token'].message_type = _TOKENPROTO
_CANCELDELEGATIONTOKENREQUESTPROTO.fields_by_name['token'].message_type = _TOKENPROTO
DESCRIPTOR.message_types_by_name['TokenProto'] = _TOKENPROTO
DESCRIPTOR.message_types_by_name['GetDelegationTokenRequestProto'] = _GETDELEGATIONTOKENREQUESTPROTO
DESCRIPTOR.message_types_by_name['GetDelegationTokenResponseProto'] = _GETDELEGATIONTOKENRESPONSEPROTO
DESCRIPTOR.message_types_by_name['RenewDelegationTokenRequestProto'] = _RENEWDELEGATIONTOKENREQUESTPROTO
DESCRIPTOR.message_types_by_name['RenewDelegationTokenResponseProto'] = _RENEWDELEGATIONTOKENRESPONSEPROTO
DESCRIPTOR.message_types_by_name['CancelDelegationTokenRequestProto'] = _CANCELDELEGATIONTOKENREQUESTPROTO
DESCRIPTOR.message_types_by_name['CancelDelegationTokenResponseProto'] = _CANCELDELEGATIONTOKENRESPONSEPROTO

class TokenProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TOKENPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.common.TokenProto)

class GetDelegationTokenRequestProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETDELEGATIONTOKENREQUESTPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.common.GetDelegationTokenRequestProto)

class GetDelegationTokenResponseProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETDELEGATIONTOKENRESPONSEPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.common.GetDelegationTokenResponseProto)

class RenewDelegationTokenRequestProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RENEWDELEGATIONTOKENREQUESTPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.common.RenewDelegationTokenRequestProto)

class RenewDelegationTokenResponseProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RENEWDELEGATIONTOKENRESPONSEPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.common.RenewDelegationTokenResponseProto)

class CancelDelegationTokenRequestProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CANCELDELEGATIONTOKENREQUESTPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.common.CancelDelegationTokenRequestProto)

class CancelDelegationTokenResponseProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CANCELDELEGATIONTOKENRESPONSEPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.common.CancelDelegationTokenResponseProto)

# @@protoc_insertion_point(module_scope)
