#!/bin/bash
GH_PAGES_SOURCES="doc/source snakebite doc/Makefile"
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
NEW_COMMIT_MESSAGE=$(git log ${CURRENT_BRANCH} -1 --pretty=short --abbrev-commit)

pushd ..
git checkout gh-pages
rm -rf build _sources _static
git checkout ${CURRENT_BRANCHc} ${GH_PAGES_SOURCES}
git reset HEAD
popd
make html
mv -fv html/* ..
pushd ..
rm -rf ${GH_PAGES_SOURCES} doc/html
git add -A
git ci -m "Generated gh-pages for ${NEW_COMMIT_MESSAGE}" && git push github gh-pages 
git checkout ${CURRENT_BRANCH}
